name: beacons_plugin
description: A new flutter plugin project.
version: 0.0.1
author: Umair Adil
homepage: https://github.com/umair13adil/simple_beacons_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.umair.beacons_plugin
        pluginClass: BeaconsPlugin
      ios:
        pluginClass: BeaconsPlugin
